### ISSUE TITLE
Uses camlp4

### ISSUE THREAD

**Issue by glondu** [garrigue/lablgl#1] opened 2019-08-03 10:48 UTC
As written [here](https://github.com/ocaml/camlp4/blob/trunk/README.md), camlp4 is deprecated and might never be updated for OCaml 4.08.0. Please consider using camlp5 or a ppx instead.

**Comment by XVilka** [comment] 2019-08-07 07:00
It is used for parsing mainly - so it is easier to switch to [sedlex](https://github.com/ocaml-community/sedlex) or mehrir instead, only two very small files are affected, so the change is trivial:
- https://github.com/garrigue/lablgl/blob/master/src/var2def.ml
- https://github.com/garrigue/lablgl/blob/master/src/var2switch.ml

**Comment by garrigue** [comment] 2019-08-07 07:05
While the problem is indeed simple in lablGL, as the parsers are very simple, the situation is more difficult with LablGtk, which uses a much more complex parser using stream parser.

A temporary solution is to switch to camlp5, as the stream parser syntax should be compatible.
In the long run, the question is whether there is any plan support stream parsers again in vanilla ocaml.

**Comment by garrigue** [comment] 2019-08-07 08:08
Fixed in new release LablGL 1.06. The dependency now only exists only during development, and camlp5 can be used as replacement.

**Comment by garrigue** [comment] 2019-08-12 04:56
Fixed in https://github.com/garrigue/lablgl/commit/d0fd3cb1d1ca345e47ea198aead3dce727650ae4.
The only remaining dependency is on https://github.com/camlp5/camlp5, for developers of lablGL itself (the processed file is in the repository).

**Closed by garrigue** 2019-08-12 04:56 UTC
